name: Cypress Tests
on:  
  push:
    branches:
      - main
  schedule:
    # Programa la ejecución de lunes a viernes a las 8 a.m.
    - cron: '0 8 * * 1-5'
  workflow_dispatch: # Esto permite la ejecución manual


jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # Runs tests in parallel with matrix strategy 
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [1,2] # Uses 2 parallel instances
    steps:
      - name: Checkout
        uses: actions/checkout@v4
       # Ejecuta las pruebas de Cypress
      - name: Cypress run
        # Acción oficial de Cypress
        uses: cypress-io/github-action@v6
        with:
          # Starts web server for E2E tests - replace with your own server invocation
          # https://docs.cypress.io/guides/continuous-integration/introduction#Boot-your-server
          #build: npm run build
          start: npm start
          browser: chrome
          #wait-on: 'http://localhost:3000' # Waits for above
          # Records to Cypress Cloud 
          record: true
          parallel: true # Runs test in parallel using settings 
          #Obtener artefactos
      - name: Upload Cypress Screenshots-${{ github.run_id }} # Nombre del artefacto con ID de ejecución   
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots-${{ github.run_id }}
            # Ruta para las capturas de pantalla deseadas
          path:       |
              cypress/screenshots/** 
              cypress/cypress-image-diff-screenshots/** 
      - name: Upload Cypress Video-${{ github.run_id }} # Nombre del artefacto con ID de ejecución
        uses: actions/upload-artifact@v4
        if: always()
        with:
              name: cypress-videos-${{ github.run_id }}
              path: cypress/videos
          
    env:
          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
          # in GitHub repo → Settings → Secrets → Actions
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}

     
